/* ==UserScript==
// @name         ka-deshittify
// @namespace    https://github.com/patrickkfkan/patreon-dl
// @version      1.0.0
// @description  Blendet Bauvertriebsanzeigen auf Kleinanzeigen.de anhand einer Blockliste von Anbieternamen aus.
// @author       Generated by OpenAI's ChatGPT
// @match        https://www.kleinanzeigen.de/*
// @grant        none
// @run-at       document-end
// ==/UserScript== */

(() => {
  'use strict';

  const SCRIPT_NAME = 'ka-deshittify';
  const STORAGE_KEY = `${SCRIPT_NAME}:settings`;
  const DEFAULT_BLOCKED_NAMES = [
    'massa haus',
    'immola',
    'monday!',
    'bien-zenker',
    'town & country',
    'fingerhaus',
    'allkauf',
    'scanhaus',
    'living haus',
    'danwood',
    'viebrockhaus',
    'okal haus'
  ];

  const ICON = '🚫';
  let blockedEntries = [];

  const consolePrefix = `[${SCRIPT_NAME}]`;

  function normalizeName(input) {
    if (!input) {
      return '';
    }

    return String(input)
      .normalize('NFKD')
      .replace(/\p{Diacritic}/gu, '')
      .replace(/[\u00A0\u200B\u200C\u200D\uFEFF]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim()
      .toLowerCase();
  }

  function uniqueNormalized(list) {
    const map = new Map();

    for (const entry of Array.isArray(list) ? list : []) {
      const label = typeof entry === 'string' ? entry.trim() : '';

      if (!label) {
        continue;
      }

      const key = normalizeName(label);

      if (!key) {
        continue;
      }

      if (!map.has(key)) {
        map.set(key, label);
      }
    }

    return Array.from(map.values());
  }

  function loadStorage() {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);

      if (!raw) {
        return { additions: [], removals: [] };
      }

      const data = JSON.parse(raw);

      if (!data || typeof data !== 'object') {
        return { additions: [], removals: [] };
      }

      return {
        additions: uniqueNormalized(data.additions),
        removals: uniqueNormalized(data.removals)
      };
    } catch (error) {
      console.warn(consolePrefix, 'Konnte gespeicherte Einstellungen nicht laden:', error);
      return { additions: [], removals: [] };
    }
  }

  let storage = loadStorage();

  function saveStorage() {
    try {
      localStorage.setItem(
        STORAGE_KEY,
        JSON.stringify({
          additions: storage.additions,
          removals: storage.removals
        })
      );
    } catch (error) {
      console.warn(consolePrefix, 'Konnte Einstellungen nicht speichern:', error);
    }
  }

  function buildBlockedEntries() {
    const entries = new Map();

    for (const name of DEFAULT_BLOCKED_NAMES) {
      const normalized = normalizeName(name);

      if (!normalized) {
        continue;
      }

      entries.set(normalized, { label: name, source: 'default' });
    }

    for (const name of storage.removals) {
      const normalized = normalizeName(name);

      if (normalized) {
        entries.delete(normalized);
      }
    }

    for (const name of storage.additions) {
      const normalized = normalizeName(name);

      if (!normalized) {
        continue;
      }

      entries.set(normalized, { label: name, source: 'custom' });
    }

    blockedEntries = Array.from(entries.entries());
  }

  buildBlockedEntries();

  function log(...args) {
    console.log(consolePrefix, ...args);
  }

  function hideListItem(listItem, reason) {
    if (!(listItem instanceof HTMLElement)) {
      return;
    }

    const currentReason = listItem.getAttribute('data-ka-deshittify-reason');

    if (!currentReason) {
      listItem.dataset.kaDeshittifyOriginalDisplay = listItem.style.display || '';
      log(ICON, 'Anzeige ausgeblendet durch', reason, listItem);
    }

    listItem.style.setProperty('display', 'none', 'important');
    listItem.setAttribute('aria-hidden', 'true');
    listItem.setAttribute('data-ka-deshittify-reason', reason);
  }

  function showListItem(listItem) {
    if (!(listItem instanceof HTMLElement)) {
      return;
    }

    const originalDisplay = listItem.dataset.kaDeshittifyOriginalDisplay;

    if (originalDisplay) {
      listItem.style.display = originalDisplay;
    } else {
      listItem.style.removeProperty('display');
    }

    listItem.removeAttribute('aria-hidden');
    listItem.removeAttribute('data-ka-deshittify-reason');
    delete listItem.dataset.kaDeshittifyOriginalDisplay;
  }

  function findMatch(text) {
    const normalizedText = normalizeName(text);

    if (!normalizedText) {
      return null;
    }

    for (const [needle, meta] of blockedEntries) {
      if (normalizedText.includes(needle)) {
        return meta.label;
      }
    }

    return null;
  }

  function evaluateArticle(article) {
    if (!(article instanceof HTMLElement)) {
      return;
    }

    const parentItem = article.closest('li.ad-listitem');

    if (!parentItem) {
      return;
    }

    const match = findMatch(article.textContent || '');

    if (match) {
      hideListItem(parentItem, match);
    } else if (parentItem.hasAttribute('data-ka-deshittify-reason')) {
      showListItem(parentItem);
    }
  }

  function evaluateListItem(listItem) {
    if (!(listItem instanceof HTMLElement)) {
      return;
    }

    const article = listItem.querySelector('article.aditem');

    if (article) {
      evaluateArticle(article);
    }
  }

  function rescanAll() {
    const items = document.querySelectorAll('li.ad-listitem article.aditem');

    for (const article of items) {
      evaluateArticle(article);
    }
  }

  function handleNode(node) {
    if (!(node instanceof HTMLElement)) {
      return;
    }

    if (node.matches('li.ad-listitem')) {
      evaluateListItem(node);
    }

    const items = node.querySelectorAll('li.ad-listitem');

    for (const item of items) {
      evaluateListItem(item);
    }
  }

  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type !== 'childList') {
        continue;
      }

      if (mutation.target instanceof HTMLElement && mutation.target.matches('li.ad-listitem')) {
        evaluateListItem(mutation.target);
      }

      for (const node of mutation.addedNodes) {
        handleNode(node);
      }
    }
  });

  observer.observe(document.body, { childList: true, subtree: true });

  rescanAll();

  function addBlockedName(name) {
    const label = typeof name === 'string' ? name.trim() : '';
    const normalized = normalizeName(label);

    if (!normalized) {
      return false;
    }

    const additionsMap = new Map(storage.additions.map((item) => [normalizeName(item), item]));
    const removalsMap = new Map(storage.removals.map((item) => [normalizeName(item), item]));

    const already = additionsMap.get(normalized);

    if (already) {
      return false;
    }

    additionsMap.set(normalized, label);
    removalsMap.delete(normalized);

    storage = {
      additions: Array.from(additionsMap.values()),
      removals: Array.from(removalsMap.values())
    };

    saveStorage();
    buildBlockedEntries();
    rescanAll();

    return true;
  }

  function removeBlockedName(name) {
    const label = typeof name === 'string' ? name.trim() : '';
    const normalized = normalizeName(label);

    if (!normalized) {
      return false;
    }

    const additionsMap = new Map(storage.additions.map((item) => [normalizeName(item), item]));
    const removalsMap = new Map(storage.removals.map((item) => [normalizeName(item), item]));

    if (additionsMap.has(normalized)) {
      additionsMap.delete(normalized);
    } else {
      removalsMap.set(normalized, label || additionsMap.get(normalized) || DEFAULT_BLOCKED_NAMES.find((entry) => normalizeName(entry) === normalized) || label);
    }

    storage = {
      additions: Array.from(additionsMap.values()),
      removals: Array.from(removalsMap.values())
    };

    saveStorage();
    buildBlockedEntries();
    rescanAll();

    return true;
  }

  function resetCustomizations() {
    storage = { additions: [], removals: [] };
    saveStorage();
    buildBlockedEntries();
    rescanAll();
  }

  const api = {
    version: '1.0.0',
    listAll() {
      return blockedEntries.map(([, meta]) => meta.label);
    },
    listDefaults() {
      return DEFAULT_BLOCKED_NAMES.slice();
    },
    listCustom() {
      return {
        additions: storage.additions.slice(),
        removals: storage.removals.slice()
      };
    },
    add(name) {
      const result = addBlockedName(name);

      if (result) {
        log('Blockliste erweitert um', name);
      }

      return result;
    },
    remove(name) {
      const result = removeBlockedName(name);

      if (result) {
        log('Eintrag aus Blockliste entfernt oder deaktiviert:', name);
      }

      return result;
    },
    reset() {
      resetCustomizations();
      log('Benutzerdefinierte Einstellungen zurückgesetzt.');
    },
    test(text) {
      return findMatch(text);
    }
  };

  window.kaDeshittify = api;

  log('aktiv. Konfiguration über window.kaDeshittify möglich.');
})();
